/*

 BACKGROUNDTILESANDHOOPS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 57

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __backgroundTilesAndHoops_h_INCLUDE
#define __backgroundTilesAndHoops_h_INCLUDE

/* Bank of tiles. */
#define bgTilesBank 0

/* Super Gameboy palette 0 */
#define bgTilesSGBPal0c0 6076
#define bgTilesSGBPal0c1 8935
#define bgTilesSGBPal0c2 6596
#define bgTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bgTilesSGBPal1c0 6076
#define bgTilesSGBPal1c1 8935
#define bgTilesSGBPal1c2 6596
#define bgTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bgTilesSGBPal2c0 6076
#define bgTilesSGBPal2c1 8935
#define bgTilesSGBPal2c2 6596
#define bgTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bgTilesSGBPal3c0 6076
#define bgTilesSGBPal3c1 8935
#define bgTilesSGBPal3c2 6596
#define bgTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bgTilesCGBPal0c0 31582
#define bgTilesCGBPal0c1 31534
#define bgTilesCGBPal0c2 28960
#define bgTilesCGBPal0c3 99

/* Gameboy Color palette 1 */
#define bgTilesCGBPal1c0 31582
#define bgTilesCGBPal1c1 11647
#define bgTilesCGBPal1c2 282
#define bgTilesCGBPal1c3 99

/* Gameboy Color palette 2 */
#define bgTilesCGBPal2c0 31582
#define bgTilesCGBPal2c1 10221
#define bgTilesCGBPal2c2 3712
#define bgTilesCGBPal2c3 99

/* Gameboy Color palette 3 */
#define bgTilesCGBPal3c0 31582
#define bgTilesCGBPal3c1 10238
#define bgTilesCGBPal3c2 761
#define bgTilesCGBPal3c3 99

/* Gameboy Color palette 4 */
#define bgTilesCGBPal4c0 31582
#define bgTilesCGBPal4c1 31358
#define bgTilesCGBPal4c2 24604
#define bgTilesCGBPal4c3 99

/* Gameboy Color palette 5 */
#define bgTilesCGBPal5c0 6076
#define bgTilesCGBPal5c1 8935
#define bgTilesCGBPal5c2 6596
#define bgTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bgTilesCGBPal6c0 6076
#define bgTilesCGBPal6c1 8935
#define bgTilesCGBPal6c2 6596
#define bgTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bgTilesCGBPal7c0 6076
#define bgTilesCGBPal7c1 8935
#define bgTilesCGBPal7c2 6596
#define bgTilesCGBPal7c3 5344

/* CGB palette entries. */
#define bgTilesCGB0 0
#define bgTilesCGB1 0
#define bgTilesCGB2 0
#define bgTilesCGB3 0
#define bgTilesCGB4 0
#define bgTilesCGB5 0
#define bgTilesCGB6 0
#define bgTilesCGB7 0
#define bgTilesCGB8 0
#define bgTilesCGB9 4
#define bgTilesCGB10 4
#define bgTilesCGB11 4
#define bgTilesCGB12 4
#define bgTilesCGB13 4
#define bgTilesCGB14 4
#define bgTilesCGB15 4
#define bgTilesCGB16 4
#define bgTilesCGB17 1
#define bgTilesCGB18 1
#define bgTilesCGB19 1
#define bgTilesCGB20 1
#define bgTilesCGB21 4
#define bgTilesCGB22 1
#define bgTilesCGB23 1
#define bgTilesCGB24 1
#define bgTilesCGB25 1
#define bgTilesCGB26 2
#define bgTilesCGB27 2
#define bgTilesCGB28 2
#define bgTilesCGB29 2
#define bgTilesCGB30 0
#define bgTilesCGB31 2
#define bgTilesCGB32 2
#define bgTilesCGB33 2
#define bgTilesCGB34 2
#define bgTilesCGB35 3
#define bgTilesCGB36 3
#define bgTilesCGB37 3
#define bgTilesCGB38 3
#define bgTilesCGB39 0
#define bgTilesCGB40 3
#define bgTilesCGB41 3
#define bgTilesCGB42 3
#define bgTilesCGB43 3
#define bgTilesCGB44 3
#define bgTilesCGB45 4
#define bgTilesCGB46 4
#define bgTilesCGB47 4
#define bgTilesCGB48 4
#define bgTilesCGB49 4
#define bgTilesCGB50 0
#define bgTilesCGB51 0
#define bgTilesCGB52 0
#define bgTilesCGB53 0
#define bgTilesCGB54 1
#define bgTilesCGB55 2
#define bgTilesCGB56 3
#define bgTilesCGB57 4
/* Start of tile array. */
extern const unsigned char bgTiles[];

#endif

/* End of BACKGROUNDTILESANDHOOPS.H */
