/*

 BALLTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ballTiles_h_INCLUDE
#define __ballTiles_h_INCLUDE

/* Bank of tiles. */
#define BallTilesBank 0

/* Super Gameboy palette 0 */
#define BallTilesSGBPal0c0 6076
#define BallTilesSGBPal0c1 8935
#define BallTilesSGBPal0c2 6596
#define BallTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BallTilesSGBPal1c0 6076
#define BallTilesSGBPal1c1 8935
#define BallTilesSGBPal1c2 6596
#define BallTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BallTilesSGBPal2c0 6076
#define BallTilesSGBPal2c1 8935
#define BallTilesSGBPal2c2 6596
#define BallTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BallTilesSGBPal3c0 6076
#define BallTilesSGBPal3c1 8935
#define BallTilesSGBPal3c2 6596
#define BallTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BallTilesCGBPal0c0 31582
#define BallTilesCGBPal0c1 31534
#define BallTilesCGBPal0c2 28960
#define BallTilesCGBPal0c3 11329

/* Gameboy Color palette 1 */
#define BallTilesCGBPal1c0 31582
#define BallTilesCGBPal1c1 11647
#define BallTilesCGBPal1c2 282
#define BallTilesCGBPal1c3 1102

/* Gameboy Color palette 2 */
#define BallTilesCGBPal2c0 31582
#define BallTilesCGBPal2c1 10221
#define BallTilesCGBPal2c2 3712
#define BallTilesCGBPal2c3 1378

/* Gameboy Color palette 3 */
#define BallTilesCGBPal3c0 31582
#define BallTilesCGBPal3c1 10238
#define BallTilesCGBPal3c2 761
#define BallTilesCGBPal3c3 1550

/* Gameboy Color palette 4 */
#define BallTilesCGBPal4c0 31582
#define BallTilesCGBPal4c1 31358
#define BallTilesCGBPal4c2 24604
#define BallTilesCGBPal4c3 99

/* Gameboy Color palette 5 */
#define BallTilesCGBPal5c0 6076
#define BallTilesCGBPal5c1 8935
#define BallTilesCGBPal5c2 6596
#define BallTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BallTilesCGBPal6c0 6076
#define BallTilesCGBPal6c1 8935
#define BallTilesCGBPal6c2 6596
#define BallTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BallTilesCGBPal7c0 6076
#define BallTilesCGBPal7c1 8935
#define BallTilesCGBPal7c2 6596
#define BallTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char BallTiles[];

#endif

/* End of BALLTILES.H */
