/*

 MAINLEVELBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : levelBackground.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mainLevelBackground_h_INCLUDE
#define __mainLevelBackground_h_INCLUDE

#define MainLevelBackgroundWidth 20
#define MainLevelBackgroundHeight 18
#define MainLevelBackgroundBank 0

#define MainLevelBackground MainLevelBackgroundPLN0
extern const unsigned char MainLevelBackgroundPLN0[];
extern const unsigned char MainLevelBackgroundPLN1[];

#endif

/* End of MAINLEVELBACKGROUND.H */
